baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "chi's handbook"
theme= 'hugo-book'

[params]
BookTheme = 'auto'
BookSection = '*'
BookRepo = 'https://github.com/realZhangChi/handbook'
BookCommitPath = 'commit'